[build]
  publish = "public"
  command = "yarn build"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.19.1"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
